falco:
  image:
    tag: 0.23.0

  podSecurityPolicy:
    # Create a podSecurityPolicy
    create: true

  ebpf:
    # Enable eBPF support for Falco
    enabled: true

  daemonset:
    podAnnotations:
      ad.datadoghq.com/falco.logs: "[{\"source\": \"falco\"}]"
    
  falco:
    jsonOutput: true

  customRules:
    new_rules: |-
      - rule: shell_in_container
        desc: notice shell activity within a container
        condition: evt.type=open and container.id != host and proc.name = bash
        output: shell in a container (user=%user.name container_id=%container.id container_name=%container.name shell=%proc.name parent=%proc.pname cmdline=%proc.cmdline)
        priority: WARNING
