image:
  tag: 0.20.0

podSecurityPolicy:
  # Create a podSecurityPolicy
  create: true

ebpf:
  # Enable eBPF support for Falco
  enabled: true

#daemonset:
#  env:
#    - name: BPF_PROBE
#      value:
#    - name: SYSDIG_BPF_PROBE
#      value: "/root/.falco/falco-probe-bpf.o"
