falco:
  image:
    tag: 0.23.0

  podSecurityPolicy:
    # Create a podSecurityPolicy
    create: true

  ebpf:
    # Enable eBPF support for Falco
    enabled: true

  daemonset:
    podAnnotations:
      ad.datadoghq.com/falco.logs: "[{\"source\": \"falco\"}]"
    
  falco:
    jsonOutput: true
    
    rulesFile:
      - /aaaaa/lovely_rules.yaml
      - /etc/falco/falco_rules.yaml
      - /etc/falco/falco_rules.local.yaml
      - /etc/falco/k8s_audit_rules.yaml
      - /etc/falco/rules.d
      - /etc/falco/lovely_rules.yaml
