falco:
  image:
    tag: 0.23.0

  podSecurityPolicy:
    # Create a podSecurityPolicy
    create: true

  ebpf:
    # Enable eBPF support for Falco
    enabled: true

  daemonset:
    podAnnotations:
      ad.datadoghq.com/falco.logs: "[{\"source\": \"falco\"}]"
    
  falco:
    jsonOutput: true
    
  customRules:
    new_rules: |-
      - rule: Terminal shell in container       
        priority: CRITICAL 
